# Generated by Django 2.0.7 on 2018-08-23 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coachdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coachname', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['coachname'],
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footeritems', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['footeritems'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuitem', models.CharField(max_length=20)),
                ('menuitemdesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platformno', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['platformno'],
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=20)),
                ('siteinfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Traindetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.IntegerField(max_length=5)),
                ('train_name', models.CharField(max_length=30)),
                ('train_dep', models.TimeField(blank=True, null=True)),
                ('train_arr', models.TimeField(blank=True, null=True)),
                ('train_source', models.CharField(blank=True, max_length=20)),
                ('train_destination', models.CharField(blank=True, max_length=20)),
                ('e_train_dep', models.TimeField(blank=True, null=True)),
                ('e_train_arr', models.TimeField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['train_name'],
            },
        ),
        migrations.CreateModel(
            name='Trainlineup',
            fields=[
                ('lineup', models.IntegerField(max_length=10)),
                ('coachdet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pmanage.Coachdetails')),
            ],
            options={
                'ordering': ['lineup'],
            },
        ),
        migrations.AddField(
            model_name='platform',
            name='traindetails',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pmanage.Traindetails'),
        ),
    ]
